export type BrowserTypes =
  | "Chrome"
  | "Firefox"
  | "Opera"
  | "Yandex"
  | "Safari"
  | "Internet Explorer"
  | "Edge"
  | "Chromium"
  | "IE"
  | "Mobile Safari"
  | "Edge Chromium"
  | "MIUI Browser"
  | "Samsung Browser"
  | "none";
