import { BrowserTypes } from "./BrowserTypes";
import { DeviceTypes } from "./DeviceTypes";
import { OsTypes } from "./OsTypes";

export interface Who {
  isReactNativeApp: boolean;
  isReactNativeAppIOS: boolean;
  isReactNativeAppAndroid: boolean;
  isReactNativeAppWeb: boolean;
  isExpoApp: boolean;
  isReactApp: boolean;
  isNextApp: boolean;
  isTWA: boolean;
  isPWAStandalone: boolean;
  isServerApp: boolean;
  isCI: boolean;
  isTestRun: boolean;
  isCypressTestRun: boolean;
  isJestTestRun: boolean;
  isBrowser: boolean;
  isMobile: boolean;
  isDesktop: boolean;
  isMobileOnly: boolean;
  isTablet: boolean;
  isSmartTV: boolean;
  isWearable: boolean;
  isConsole: boolean;
  isEmbedded: boolean;
  isAndroid: boolean;
  isWinPhone: boolean;
  isIOS: boolean;
  isChrome: boolean;
  isFirefox: boolean;
  isSafari: boolean;
  isOpera: boolean;
  isIE: boolean;
  isEdge: boolean;
  isYandex: boolean;
  isChromium: boolean;
  isMobileSafari: boolean;
  isSamsungBrowser: boolean;
  osVersion: string;
  osName: OsTypes;
  fullBrowserVersion: string;
  browserVersion: string;
  browserName: BrowserTypes;
  mobileVendor: string;
  mobileModel: string;
  engineName: string;
  engineVersion: string;
  deviceType: DeviceTypes;
  isIOS13: boolean;
  isIPhone13: boolean;
  isIPad13: boolean;
  isIPod13: boolean;
  isElectron: boolean;
  isEdgeChromium: boolean;
  isLegacyEdge: boolean;
  isWindows: boolean;
  isMacOs: boolean;
}
